# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/users')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alergia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alergias',
                'verbose_name': 'Alergia',
            },
        ),
        migrations.CreateModel(
            name='Alergico_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alérgico a Medicamentos',
                'verbose_name': 'Alérgico a Medicamento',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas',
                'verbose_name': 'Área',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_cedula', models.CharField(blank=True, choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1, null=True)),
                ('fecha_nac', models.DateField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('direccion', models.TextField()),
                ('tlf_fijo', models.CharField(blank=True, max_length=100, null=True)),
                ('tlf_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermedad_hp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_e_hp', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Enfermedades que ha padecido',
                'verbose_name': 'Enfermedad que ha padecido',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad_padece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_e_p', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Enfermedades que padece',
                'verbose_name': 'Enfermedad que padece',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_cedula', models.CharField(blank=True, choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1, null=True)),
                ('fecha_nac', models.DateField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('lugar_nac', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('madre', models.CharField(blank=True, max_length=200, null=True)),
                ('cedula_m', models.CharField(blank=True, max_length=50, null=True)),
                ('profesion_m', models.CharField(blank=True, max_length=50, null=True)),
                ('padre', models.CharField(blank=True, max_length=200, null=True)),
                ('cedula_p', models.CharField(blank=True, max_length=50, null=True)),
                ('profesion_p', models.CharField(blank=True, max_length=50, null=True)),
                ('convive', models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Ambos', 'Ambos')], default='Ambos', max_length=5, null=True)),
                ('convive_o', models.CharField(blank=True, max_length=50, null=True)),
                ('plantel_ant', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('alergias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Alergia')),
                ('alergico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Alergico_m')),
                ('enfermedad_hp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Enfermedad_hp')),
                ('enfermedad_padece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Enfermedad_padece')),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
                'verbose_name': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Area')),
            ],
            options={
                'verbose_name_plural': 'Grados',
                'verbose_name': 'Grado',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('detalle', models.TextField()),
                ('docente', models.ManyToManyField(to='administrativo.Docente')),
                ('grado', models.ManyToManyField(to='administrativo.Grado')),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'verbose_name': 'Materia',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_cedula', models.CharField(blank=True, choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1, null=True)),
                ('fecha_nac', models.DateField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tlf_oficina', models.CharField(blank=True, max_length=100, null=True)),
                ('tlf_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profesion_r', models.CharField(max_length=100)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Representantes',
                'verbose_name': 'Representante',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(blank=True, max_length=1, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Secciones',
                'verbose_name': 'Sección',
            },
        ),
        migrations.AddField(
            model_name='grado',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Seccion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Grado'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Representante'),
        ),
        migrations.AddField(
            model_name='docente',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Grado'),
        ),
    ]
