# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_auto_20160602_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentesco',
            options={'verbose_name': 'Parentesco', 'verbose_name_plural': 'Parentescos'},
        ),
    ]
