# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_auto_20160602_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='alergias',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='alergias',
            field=models.ManyToManyField(to='administrativo.Alergia'),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='alergico',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='alergico',
            field=models.ManyToManyField(to='administrativo.Alergico_m'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='convive_o',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='enfermedad_hp',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='enfermedad_hp',
            field=models.ManyToManyField(to='administrativo.Enfermedad_hp'),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='enfermedad_padece',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='enfermedad_padece',
            field=models.ManyToManyField(to='administrativo.Enfermedad_padece'),
        ),
    ]
