# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_auto_20160602_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='representante',
            name='parentesco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Parentesco'),
        ),
    ]
