# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0007_auto_20160602_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cedula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cedula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
