# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0009_auto_20160602_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial_docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Credencial_docentes',
                'verbose_name': 'Credencial_docente',
            },
        ),
        migrations.CreateModel(
            name='Historial_docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio_act', models.TextField()),
                ('fecha_ce', models.DateField(verbose_name='Fecha en que comenzó a ejercer')),
                ('plantel_ce', models.CharField(max_length=100, verbose_name='Plantel en que comenzó a ejercer')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio en el plantel')),
                ('educ_oficial_a', models.CharField(max_length=50)),
                ('educ_oficial_m', models.CharField(max_length=50)),
                ('educ_privada_a', models.CharField(max_length=50)),
                ('educ_privada_m', models.CharField(max_length=50)),
                ('total_servicio_a', models.CharField(max_length=50)),
                ('total_servicio_m', models.CharField(max_length=50)),
                ('Observaciones', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Historiales',
                'verbose_name': 'Historial',
            },
        ),
        migrations.CreateModel(
            name='Horas_docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_semanal', models.CharField(max_length=10)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Grado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Materia')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Seccion')),
            ],
        ),
        migrations.RemoveField(
            model_name='docente',
            name='area',
        ),
        migrations.AddField(
            model_name='docente',
            name='horas',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='docente',
            name='nacionalidad_act',
            field=models.CharField(default='Venezolano', max_length=100, verbose_name='Nacionalidad actual'),
        ),
        migrations.AddField(
            model_name='docente',
            name='nacionalidad_o',
            field=models.CharField(default='Venezolano', max_length=100, verbose_name='Nacionalidad originaria'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cedula_esc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Cedula Escolar'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docente',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='alergias',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='alergias',
            field=models.TextField(default='Ninguna', verbose_name='Alergia'),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='alergico',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='alergico',
            field=models.TextField(default='Ninguno', verbose_name='Alérgico a Medicamento'),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='enfermedad_hp',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='enfermedad_hp',
            field=models.TextField(default='Ninguna', verbose_name='Enfermedad que ha padecido'),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='enfermedad_padece',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='enfermedad_padece',
            field=models.TextField(default='Ninguna', verbose_name='Enfermedad que padece'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='parentesco',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Alergia',
        ),
        migrations.DeleteModel(
            name='Alergico_m',
        ),
        migrations.DeleteModel(
            name='Enfermedad_hp',
        ),
        migrations.DeleteModel(
            name='Enfermedad_padece',
        ),
        migrations.DeleteModel(
            name='Parentesco',
        ),
        migrations.AddField(
            model_name='historial_docente',
            name='docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Docente'),
        ),
    ]
