# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 00:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0010_auto_20160610_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_docente',
            old_name='Observaciones',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='horas_docente',
            name='seccion',
        ),
        migrations.AddField(
            model_name='credencial_docente',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrativo.Docente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credencial_docente',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 6, 11, 0, 59, 17, 985902, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credencial_docente',
            name='institucion_o',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credencial_docente',
            name='numero',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credencial_docente',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horas_docente',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrativo.Docente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial_docente',
            name='fecha_ce',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historial_docente',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
