# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0011_auto_20160610_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credencial_docente',
            options={'verbose_name': 'Credencial docente', 'verbose_name_plural': 'Credenciales docentes'},
        ),
        migrations.AlterModelOptions(
            name='horas_docente',
            options={'verbose_name': 'Horas docente', 'verbose_name_plural': 'Horas docentes'},
        ),
    ]
