# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0012_auto_20160610_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
