# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_categoria_f_publicacion_respuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'verbose_name': 'Asistente (Eventos)', 'verbose_name_plural': 'Asistentes (Eventos)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria (Eventos)', 'verbose_name_plural': 'Categorias (Eventos)'},
        ),
        migrations.AlterModelOptions(
            name='contenido',
            options={'verbose_name': 'Contenido (Material Educativo)', 'verbose_name_plural': 'Contenidos (Material Educativo)'},
        ),
    ]
