# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_auto_20160602_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='modified',
            new_name='actualizacion',
        ),
        migrations.RenameField(
            model_name='assistant',
            old_name='created',
            new_name='creacion',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='modified',
            new_name='actualizacion',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='created',
            new_name='creacion',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='modified',
            new_name='actualizacion',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created',
            new_name='creacion',
        ),
    ]
