# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria (Blog)', 'verbose_name_plural': 'Categorias (Blog)'},
        ),
        migrations.AlterModelOptions(
            name='comentario_blog',
            options={'verbose_name': 'Comentario  (Blog)', 'verbose_name_plural': 'Comentarios  (Blog)'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Entrada  (Blog)', 'verbose_name_plural': 'Entradas  (Blog)'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta  (Blog)', 'verbose_name_plural': 'Etiquetas  (Blog)'},
        ),
    ]
