# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20160602_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
