# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título de la Entrada'),
        ),
    ]
